# Q-2 Write a program to input eight numbers from user and display the unique numbers (onces).
set_num = set()

num1 = input("Enter the number : ")
set_num.add(int(num1))
num2 = input("Enter the number :")
set_num.add(int(num2))
num3 = input("Enter the number :")
set_num.add(int(num3))
num4 = input("Enter the number :")
set_num.add(int(num4))
num5 = input("Enter the number :")
set_num.add(int(num5))
num6 = input("Enter the number :")
set_num.add(int(num6))
num7 = input("Enter the number :")
set_num.add(int(num7))
num8 = input("Enter the number :")
set_num.add(int(num8))

print(set_num)
